In [1]:
import pandas as pd
final_df = pd.read_parquet(r"D:/variant_data/clinvar_vep_mapping.parquet")

In [2]:
final_df['Consequence'].value_counts()

Consequence
missense_variant                                                                                          2270106
synonymous_variant                                                                                         691731
intron_variant                                                                                             336913
downstream_gene_variant                                                                                    142198
splice_polypyrimidine_tract_variant,intron_variant                                                          97051
upstream_gene_variant                                                                                       93804
stop_gained                                                                                                 83572
missense_variant,splice_region_variant                                                                      75532
splice_region_variant,splice_polypyrimidine_tract_variant,intron_variant                                    74047
3_prime_UTR_variant                                                                                         63732
splice_donor_variant                                                                                        45550
splice_acceptor_variant                                                                                     40009
splice_donor_region_variant,intron_variant                                                                  27181
splice_region_variant,synonymous_variant                                                                    24000
splice_region_variant,intron_variant                                                                        23841
5_prime_UTR_variant                                                                                         17839
splice_donor_5th_base_variant,intron_variant                                                                13543
stop_gained,splice_region_variant                                                                            4278
intergenic_variant                                                                                           3258
start_lost                                                                                                   3033
intron_variant,non_coding_transcript_variant                                                                 1533
non_coding_transcript_exon_variant                                                                           1521
stop_lost                                                                                                     953
splice_region_variant,5_prime_UTR_variant                                                                     673
stop_retained_variant                                                                                         441
splice_region_variant,3_prime_UTR_variant                                                                     106
start_lost,splice_region_variant                                                                               96
splice_region_variant,non_coding_transcript_exon_variant                                                       71
splice_region_variant,splice_polypyrimidine_tract_variant,intron_variant,non_coding_transcript_variant         59
splice_donor_variant,non_coding_transcript_variant                                                             59
splice_polypyrimidine_tract_variant,intron_variant,non_coding_transcript_variant                               55
splice_acceptor_variant,non_coding_transcript_variant                                                          46
splice_donor_region_variant,intron_variant,non_coding_transcript_variant                                       33
coding_sequence_variant                                                                                        32
intron_variant,NMD_transcript_variant                                                                          21
splice_donor_5th_base_variant,intron_variant,non_coding_transcript_variant                                     15
3_prime_UTR_variant,NMD_transcript_variant                                                                     15
stop_lost,splice_region_variant                                                                                15
mature_miRNA_variant                                                                                            9
regulatory_region_variant                                                                                       4
splice_region_variant,intron_variant,non_coding_transcript_variant                                              4
splice_region_variant,stop_retained_variant                                                                     4
splice_region_variant,coding_sequence_variant                                                                   3
missense_variant,splice_donor_region_variant                                                                    2
missense_variant,NMD_transcript_variant                                                                         1
incomplete_terminal_codon_variant,coding_sequence_variant                                                       1
TF_binding_site_variant                                                                                         1
splice_region_variant,intron_variant,NMD_transcript_variant                                                     1
Name: count, dtype: int64

In [3]:
final_df.isnull().sum()

#AlleleID                           0
Type                                0
Name                                0
GeneID                              0
GeneSymbol                        748
HGNC_ID                          4484
ClinicalSignificance           235824
ClinSigSimple                       0
PhenotypeIDS                    48385
PhenotypeList                     562
Origin                              0
OriginSimple                        0
Assembly                            0
ChromosomeAccession                 0
CHROM                               0
Start                               0
Stop                                0
ReviewStatus                   235824
VariationID                         0
POS                                 0
REF                                 0
ALT                                 0
SomaticClinicalImpact         4136138
ReviewStatusClinicalImpact    4136138
Oncogenicity                  4135773
ReviewStatusOncogenicity      4135773
Location                          603
Allele                            603
Gene                              603
SYMBOL                            603
Feature                           603
Feature_type                      603
Consequence                       603
cDNA_position                     603
CDS_position                      603
Protein_position                  603
Amino_acids                       603
Codons                            603
MANE_SELECT                       603
CANONICAL                         603
AF                                603
gnomADe_AF                        603
SpliceAI_pred                     603
phyloP100way_vertebrate           603
phyloP470way_mammalian            603
phyloP17way_primate               603
phastCons100way_vertebrate        603
phastCons470way_mammalian         603
phastCons17way_primate            603
GERP++_RS                         603
GERP++_NR                         603
GERP_92_mammals                   603
dtype: int64

In [4]:
import numpy as np

# Danh sách giá trị cần kiểm tra
invalid_values = ["-", "na", "n/a", "NA", "N/A", "NaN", "nan"]

# Thay thế toàn bộ giá trị lỗi trong toàn DataFrame bằng np.nan
final_df = final_df.replace(invalid_values, np.nan)
final_df.isnull().sum()

C:\Users\Dung\AppData\Local\Temp\ipykernel_22660\2278691254.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  final_df = final_df.replace(invalid_values, np.nan)

#AlleleID                           0
Type                                0
Name                                0
GeneID                              0
GeneSymbol                        748
HGNC_ID                          4484
ClinicalSignificance           235824
ClinSigSimple                       0
PhenotypeIDS                    48385
PhenotypeList                     562
Origin                              0
OriginSimple                        0
Assembly                            0
ChromosomeAccession                 0
CHROM                               0
Start                               0
Stop                                0
ReviewStatus                   235824
VariationID                         0
POS                                 0
REF                                 0
ALT                                 0
SomaticClinicalImpact         4136138
ReviewStatusClinicalImpact    4136138
Oncogenicity                  4135773
ReviewStatusOncogenicity      4135773
Location                          603
Allele                            603
Gene                             3866
SYMBOL                           6286
Feature                          3861
Feature_type                     3861
Consequence                       603
cDNA_position                  899829
CDS_position                   983795
Protein_position               983795
Amino_acids                    983830
Codons                         983795
MANE_SELECT                     18808
CANONICAL                        7035
AF                            3584119
gnomADe_AF                    1422895
SpliceAI_pred                 4137595
phyloP100way_vertebrate       1702116
phyloP470way_mammalian        1892392
phyloP17way_primate           1702179
phastCons100way_vertebrate    1702116
phastCons470way_mammalian     1704680
phastCons17way_primate        1702179
GERP++_RS                     1714580
GERP++_NR                     1714580
GERP_92_mammals               2388814
dtype: int64

In [5]:
final_df = final_df[final_df['Consequence'] == 'missense_variant']
final_df.isnull().sum()

#AlleleID                           0
Type                                0
Name                                0
GeneID                              0
GeneSymbol                          3
HGNC_ID                          1158
ClinicalSignificance            41168
ClinSigSimple                       0
PhenotypeIDS                    18992
PhenotypeList                     364
Origin                              0
OriginSimple                        0
Assembly                            0
ChromosomeAccession                 0
CHROM                               0
Start                               0
Stop                                0
ReviewStatus                    41168
VariationID                         0
POS                                 0
REF                                 0
ALT                                 0
SomaticClinicalImpact         2269037
ReviewStatusClinicalImpact    2269037
Oncogenicity                  2269082
ReviewStatusOncogenicity      2269082
Location                            0
Allele                              0
Gene                                0
SYMBOL                             71
Feature                             0
Feature_type                        0
Consequence                         0
cDNA_position                       0
CDS_position                        0
Protein_position                    0
Amino_acids                         0
Codons                              0
MANE_SELECT                      5565
CANONICAL                         605
AF                            2057740
gnomADe_AF                     730121
SpliceAI_pred                 2270106
phyloP100way_vertebrate          1827
phyloP470way_mammalian         180485
phyloP17way_primate              1887
phastCons100way_vertebrate       1827
phastCons470way_mammalian        4316
phastCons17way_primate           1887
GERP++_RS                       13800
GERP++_NR                       13800
GERP_92_mammals                626983
dtype: int64

In [6]:
final_df = final_df.dropna(subset=['ClinicalSignificance', 'Consequence', 'SYMBOL', 'MANE_SELECT', 'CANONICAL'])
final_df.isnull().sum()

#AlleleID                           0
Type                                0
Name                                0
GeneID                              0
GeneSymbol                          0
HGNC_ID                          1130
ClinicalSignificance                0
ClinSigSimple                       0
PhenotypeIDS                    18751
PhenotypeList                     357
Origin                              0
OriginSimple                        0
Assembly                            0
ChromosomeAccession                 0
CHROM                               0
Start                               0
Stop                                0
ReviewStatus                        0
VariationID                         0
POS                                 0
REF                                 0
ALT                                 0
SomaticClinicalImpact         2223203
ReviewStatusClinicalImpact    2223203
Oncogenicity                  2223230
ReviewStatusOncogenicity      2223230
Location                            0
Allele                              0
Gene                                0
SYMBOL                              0
Feature                             0
Feature_type                        0
Consequence                         0
cDNA_position                       0
CDS_position                        0
Protein_position                    0
Amino_acids                         0
Codons                              0
MANE_SELECT                         0
CANONICAL                           0
AF                            2015194
gnomADe_AF                     696807
SpliceAI_pred                 2223945
phyloP100way_vertebrate            44
phyloP470way_mammalian         175208
phyloP17way_primate               104
phastCons100way_vertebrate         44
phastCons470way_mammalian        2506
phastCons17way_primate            104
GERP++_RS                       11776
GERP++_NR                       11776
GERP_92_mammals                611157
dtype: int64

In [7]:
final_df['ClinicalSignificance'].value_counts().to_string()

'ClinicalSignificance\nUncertain significance                                                    1923272\nConflicting classifications of pathogenicity                               100418\nLikely benign                                                               92780\nLikely pathogenic                                                           30158\nBenign                                                                      27769\nPathogenic                                                                  20641\nBenign/Likely benign                                                        12843\nPathogenic/Likely pathogenic                                                11099\nnot provided                                                                 2879\nother                                                                         463\ndrug response                                                                 361\nno classification for the single variant                                      288\nrisk factor                                                                   130\nUncertain significance/Uncertain risk allele                                  123\nassociation                                                                    87\nno classifications from unflagged records                                      67\nAffects                                                                        66\nLikely pathogenic, low penetrance                                              63\nPathogenic; other                                                              59\nLikely risk allele                                                             43\nPathogenic; drug response                                                      36\nVUS-high                                                                       21\nConflicting classifications of pathogenicity; other                            17\nVUS-mid                                                                        17\nUncertain risk allele                                                          16\nUncertain significance/VUS-high                                                14\nConflicting classifications of pathogenicity; risk factor                      14\nLikely pathogenic/Likely risk allele                                           13\nBenign; risk factor                                                            13\nprotective                                                                     11\nLikely pathogenic; drug response                                               10\nBenign; other                                                                   9\nUncertain significance; other                                                   9\nBenign/Likely benign; other                                                     9\nVUS-low                                                                         8\nBenign; association                                                             7\nUncertain significance/VUS-mid                                                  6\nConflicting classifications of pathogenicity; association                       5\nLikely benign; other                                                            5\nPathogenic; risk factor                                                         5\nUncertain significance; drug response                                           5\nUncertain significance; risk factor                                             5\nPathogenic/Likely pathogenic/Likely risk allele                                 4\nPathogenic, low penetrance                                                      4\nBenign; drug response                                                           4\nPathogenic/Likely pathogenic; other                                             3\nPathogenic/Likely pathogenic/Pathogenic, low penetrance                         3\nUncertain significance/VUS-low                                                  3\nPathogenic/Likely risk allele                                                   3\nPathogenic/Likely pathogenic; risk factor                                       3\nBenign; protective                                                              3\nconfers sensitivity                                                             3\nPathogenic; association                                                         3\nLikely benign; drug response                                                    3\nBenign/Likely benign; drug response                                             2\nLikely pathogenic; association                                                  2\nLikely benign; drug response; other                                             2\nConflicting classifications of pathogenicity; association; risk factor          2\nConflicting classifications of pathogenicity; drug response                     2\nConflicting classifications of pathogenicity; other; risk factor                2\nPathogenic; Affects                                                             2\nBenign; Affects                                                                 2\nPathogenic/Likely pathogenic; drug response                                     2\nPathogenic/Likely pathogenic, low penetrance                                    2\nLikely benign; association                                                      1\ndrug response; other                                                            1\nLikely pathogenic/Likely pathogenic, low penetrance                             1\nprotective; risk factor                                                         1\nPathogenic/Likely pathogenic/Established risk allele                            1\nUncertain risk allele; risk factor                                              1\nLikely benign; risk factor                                                      1\nBenign/Likely benign; drug response; other                                      1\nPathogenic/Pathogenic, low penetrance; other                                    1\nPathogenic/Likely pathogenic; association                                       1\nBenign/Likely benign; association                                               1\nPathogenic/Likely pathogenic/Likely pathogenic, low penetrance                  1\nconfers sensitivity; other                                                      1\nBenign/Likely benign; other; risk factor                                        1\nConflicting classifications of pathogenicity; protective                        1\nLikely pathogenic; risk factor                                                  1\nLikely pathogenic/Pathogenic, low penetrance                                    1\nLikely benign; Affects; association                                             1\nPathogenic/Pathogenic, low penetrance; risk factor                              1\nConflicting classifications of pathogenicity; Affects                           1\nUncertain significance; Affects                                                 1\nUncertain significance; association                                             1'

In [8]:
final_df = final_df[final_df['ClinicalSignificance'].isin(['Uncertain significance'])]

In [9]:
final_df.isnull().sum()

#AlleleID                           0
Type                                0
Name                                0
GeneID                              0
GeneSymbol                          0
HGNC_ID                           628
ClinicalSignificance                0
ClinSigSimple                       0
PhenotypeIDS                    12611
PhenotypeList                      67
Origin                              0
OriginSimple                        0
Assembly                            0
ChromosomeAccession                 0
CHROM                               0
Start                               0
Stop                                0
ReviewStatus                        0
VariationID                         0
POS                                 0
REF                                 0
ALT                                 0
SomaticClinicalImpact         1923202
ReviewStatusClinicalImpact    1923202
Oncogenicity                  1923169
ReviewStatusOncogenicity      1923169
Location                            0
Allele                              0
Gene                                0
SYMBOL                              0
Feature                             0
Feature_type                        0
Consequence                         0
cDNA_position                       0
CDS_position                        0
Protein_position                    0
Amino_acids                         0
Codons                              0
MANE_SELECT                         0
CANONICAL                           0
AF                            1792814
gnomADe_AF                     623645
SpliceAI_pred                 1923272
phyloP100way_vertebrate            41
phyloP470way_mammalian         150440
phyloP17way_primate                94
phastCons100way_vertebrate         41
phastCons470way_mammalian        2182
phastCons17way_primate             94
GERP++_RS                       10538
GERP++_NR                       10538
GERP_92_mammals                528607
dtype: int64

In [10]:
final_df.describe()

,#AlleleID,GeneID,ClinSigSimple,Start,Stop,VariationID,POS,SpliceAI_pred
count,1.923272e+06,1.923272e+06,1.923272e+06,1.923272e+06,1.923272e+06,1.923272e+06,1.923272e+06,0.0
mean,2.960553e+06,3.001628e+05,1.793298e-03,7.635814e+07,7.635814e+07,2.883852e+06,7.635814e+07,NaN
std,1.255759e+06,4.908617e+06,4.230937e-02,5.722799e+07,5.722799e+07,1.200706e+06,5.722799e+07,NaN
min,1.505100e+04,-1.000000e+00,0.000000e+00,1.481400e+04,1.481400e+04,1.200000e+01,1.481400e+04,NaN
25%,2.080441e+06,5.147000e+03,0.000000e+00,3.232511e+07,3.232511e+07,2.114220e+06,3.232511e+07,NaN
50%,3.272124e+06,1.110700e+04,0.000000e+00,6.270766e+07,6.270766e+07,3.113718e+06,6.270766e+07,NaN
75%,4.016145e+06,7.915500e+04,0.000000e+00,1.128399e+08,1.128399e+08,3.901002e+06,1.128399e+08,NaN
max,4.968329e+06,1.207661e+08,1.000000e+00,2.489184e+08,2.489184e+08,4.857408e+06,2.489184e+08,NaN

In [11]:
final_df['AF'].astype(float).describe()

count    130458.000000
mean          0.000681
std           0.017810
min           0.000000
25%           0.000200
50%           0.000200
75%           0.000400
max           0.999800
Name: AF, dtype: float64

In [12]:
final_df['AF'] = final_df['AF'].astype(float)
final_df['AF'][final_df['AF'] == 0].count()

np.int64(629)

In [13]:
final_df[final_df['AF'].isnull() & final_df['gnomADe_AF'].isnull()][['AF', 'gnomADe_AF']]

         AF gnomADe_AF
2       NaN        NaN
6       NaN        NaN
7       NaN        NaN
9       NaN        NaN
13      NaN        NaN
...      ..        ...
4136877 NaN        NaN
4136929 NaN        NaN
4136934 NaN        NaN
4136947 NaN        NaN
4137250 NaN        NaN

[621222 rows x 2 columns]

In [14]:
final_df.dropna(subset=['GERP_92_mammals'], how='all', inplace=True)
final_df.dropna(subset=['phyloP470way_mammalian'], how='all', inplace=True)
final_df.dropna(subset=['GERP++_RS'], how='all', inplace=True)
final_df.dropna(subset=['GERP++_NR'], how='all', inplace=True)

In [15]:
final_df.isnull().sum()

#AlleleID                           0
Type                                0
Name                                0
GeneID                              0
GeneSymbol                          0
HGNC_ID                           399
ClinicalSignificance                0
ClinSigSimple                       0
PhenotypeIDS                     8344
PhenotypeList                      56
Origin                              0
OriginSimple                        0
Assembly                            0
ChromosomeAccession                 0
CHROM                               0
Start                               0
Stop                                0
ReviewStatus                        0
VariationID                         0
POS                                 0
REF                                 0
ALT                                 0
SomaticClinicalImpact         1281821
ReviewStatusClinicalImpact    1281821
Oncogenicity                  1281796
ReviewStatusOncogenicity      1281796
Location                            0
Allele                              0
Gene                                0
SYMBOL                              0
Feature                             0
Feature_type                        0
Consequence                         0
cDNA_position                       0
CDS_position                        0
Protein_position                    0
Amino_acids                         0
Codons                              0
MANE_SELECT                         0
CANONICAL                           0
AF                            1192046
gnomADe_AF                     406807
SpliceAI_pred                 1281863
phyloP100way_vertebrate             0
phyloP470way_mammalian              0
phyloP17way_primate                16
phastCons100way_vertebrate          0
phastCons470way_mammalian           0
phastCons17way_primate             16
GERP++_RS                           0
GERP++_NR                           0
GERP_92_mammals                     0
dtype: int64

In [16]:
final_df.replace({'AF': {np.nan: 0}}, inplace=True)
final_df.replace({'gnomADe_AF': {np.nan: 0}}, inplace=True)

In [17]:
final_df.isnull().sum()

#AlleleID                           0
Type                                0
Name                                0
GeneID                              0
GeneSymbol                          0
HGNC_ID                           399
ClinicalSignificance                0
ClinSigSimple                       0
PhenotypeIDS                     8344
PhenotypeList                      56
Origin                              0
OriginSimple                        0
Assembly                            0
ChromosomeAccession                 0
CHROM                               0
Start                               0
Stop                                0
ReviewStatus                        0
VariationID                         0
POS                                 0
REF                                 0
ALT                                 0
SomaticClinicalImpact         1281821
ReviewStatusClinicalImpact    1281821
Oncogenicity                  1281796
ReviewStatusOncogenicity      1281796
Location                            0
Allele                              0
Gene                                0
SYMBOL                              0
Feature                             0
Feature_type                        0
Consequence                         0
cDNA_position                       0
CDS_position                        0
Protein_position                    0
Amino_acids                         0
Codons                              0
MANE_SELECT                         0
CANONICAL                           0
AF                                  0
gnomADe_AF                          0
SpliceAI_pred                 1281863
phyloP100way_vertebrate             0
phyloP470way_mammalian              0
phyloP17way_primate                16
phastCons100way_vertebrate          0
phastCons470way_mammalian           0
phastCons17way_primate             16
GERP++_RS                           0
GERP++_NR                           0
GERP_92_mammals                     0
dtype: int64

In [18]:
final_df[['gnomADe_AF', 'phyloP100way_vertebrate', 'phyloP470way_mammalian', 'phyloP17way_primate', 'phastCons100way_vertebrate', 'phastCons470way_mammalian', 'phastCons17way_primate', 'GERP++_RS', 'GERP++_NR', 'GERP_92_mammals']] = final_df[['gnomADe_AF', 'phyloP100way_vertebrate', 'phyloP470way_mammalian', 'phyloP17way_primate', 'phastCons100way_vertebrate', 'phastCons470way_mammalian', 'phastCons17way_primate', 'GERP++_RS', 'GERP++_NR', 'GERP_92_mammals']].astype(float)

In [19]:
final_df.describe()

,#AlleleID,GeneID,ClinSigSimple,Start,Stop,VariationID,POS,AF,gnomADe_AF,SpliceAI_pred,phyloP100way_vertebrate,phyloP470way_mammalian,phyloP17way_primate,phastCons100way_vertebrate,phastCons470way_mammalian,phastCons17way_primate,GERP++_RS,GERP++_NR,GERP_92_mammals
count,1.281863e+06,1.281863e+06,1.281863e+06,1.281863e+06,1.281863e+06,1.281863e+06,1.281863e+06,1.281863e+06,1.281863e+06,0.0,1.281863e+06,1.281863e+06,1.281847e+06,1.281863e+06,1.281863e+06,1.281847e+06,1.281863e+06,1.281863e+06,1.281863e+06
mean,2.959158e+06,2.576865e+05,1.571931e-03,7.597543e+07,7.597543e+07,2.882762e+06,7.597543e+07,2.581750e-05,2.193345e-05,NaN,3.356391e+00,4.560916e+00,4.362641e-01,7.251675e-01,7.562839e-01,6.955303e-01,3.209197e+00,5.066096e+00,4.046282e-01
std,1.251855e+06,4.471764e+06,3.961642e-02,5.644405e+07,5.644405e+07,1.196621e+06,5.644405e+07,7.461440e-04,9.647800e-04,NaN,3.047880e+00,4.310982e+00,4.692941e-01,4.167585e-01,4.097719e-01,3.819579e-01,2.810448e+00,8.498819e-01,2.076762e+00
min,1.518000e+04,-1.000000e+00,0.000000e+00,4.550900e+04,4.550900e+04,1.410000e+02,4.550900e+04,0.000000e+00,0.000000e+00,NaN,-2.000000e+01,-2.000000e+01,-9.735000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-1.230000e+01,4.650000e-02,-1.780000e+01
25%,2.072752e+06,5.099000e+03,0.000000e+00,3.260319e+07,3.260319e+07,2.111062e+06,3.260319e+07,0.000000e+00,0.000000e+00,NaN,7.950000e-01,1.190000e+00,5.370000e-01,2.860000e-01,6.110000e-01,3.470000e-01,2.180000e+00,4.720000e+00,-7.470000e-01
50%,3.268757e+06,1.121500e+04,0.000000e+00,6.356502e+07,6.356502e+07,3.110136e+06,6.356502e+07,0.000000e+00,2.053000e-06,NaN,2.702000e+00,4.559000e+00,5.990000e-01,1.000000e+00,1.000000e+00,9.370000e-01,4.090000e+00,5.280000e+00,9.160000e-01
75%,4.009333e+06,7.909200e+04,0.000000e+00,1.111887e+08,1.111887e+08,3.894268e+06,1.111887e+08,0.000000e+00,1.163000e-05,NaN,5.777000e+00,7.692000e+00,6.760000e-01,1.000000e+00,1.000000e+00,9.940000e-01,5.160000e+00,5.650000e+00,1.860000e+00
max,4.968318e+06,1.207661e+08,1.000000e+00,2.488583e+08,2.488583e+08,4.857397e+06,2.488583e+08,4.565000e-01,6.101000e-01,NaN,1.000300e+01,1.193600e+01,7.560000e-01,1.000000e+00,1.000000e+00,1.000000e+00,6.170000e+00,6.170000e+00,1.030000e+01

In [20]:
final_df.to_parquet(r'D:/variant_data/clinvar_vus_vep_mapping_final.parquet', index=False)

In [21]:
pd.read_parquet(r'D:/variant_data/clinvar_vus_vep_mapping_final.parquet').head()

,#AlleleID,Type,Name,GeneID,GeneSymbol,HGNC_ID,ClinicalSignificance,ClinSigSimple,PhenotypeIDS,PhenotypeList,...,SpliceAI_pred,phyloP100way_vertebrate,phyloP470way_mammalian,phyloP17way_primate,phastCons100way_vertebrate,phastCons470way_mammalian,phastCons17way_primate,GERP++_RS,GERP++_NR,GERP_92_mammals
0,929889,single nucleotide variant,NM_005101.4(ISG15):c.31G>A (p.Ala11Thr),9636,ISG15,HGNC:4053,Uncertain significance,0,"MONDO:MONDO:0014502,MedGen:C4015293,OMIM:61612...",Mendelian susceptibility to mycobacterial dise...,...,NaN,0.025,1.198,0.662,0.005,0.617,0.547,0.655,4.25,-1.190
1,626468,single nucleotide variant,NM_005101.4(ISG15):c.32C>T (p.Ala11Val),9636,ISG15,HGNC:4053,Uncertain significance,0,"MONDO:MONDO:0014502,MedGen:C4015293,OMIM:61612...",Mendelian susceptibility to mycobacterial dise...,...,NaN,-2.569,-0.421,-2.140,0.000,0.000,0.396,-1.630,4.25,-2.660
2,3002551,single nucleotide variant,NM_005101.4(ISG15):c.41A>T (p.Glu14Val),9636,ISG15,HGNC:4053,Uncertain significance,0,"MONDO:MONDO:0014502,MedGen:C4015293,OMIM:61612...",Mendelian susceptibility to mycobacterial dise...,...,NaN,0.328,3.487,0.740,0.001,1.000,0.374,4.250,4.25,1.380
3,1467073,single nucleotide variant,NM_005101.4(ISG15):c.65C>T (p.Ser22Phe),9636,ISG15,HGNC:4053,Uncertain significance,0,"MONDO:MONDO:0014502,MedGen:C4015293,OMIM:61612...",Mendelian susceptibility to mycobacterial dise...,...,NaN,-0.240,0.159,0.587,0.000,0.000,0.018,0.956,4.25,0.182
4,626469,single nucleotide variant,NM_005101.4(ISG15):c.67A>G (p.Met23Val),9636,ISG15,HGNC:4053,Uncertain significance,0,"MONDO:MONDO:0014502,MedGen:C4015293,OMIM:61612...",Mendelian susceptibility to mycobacterial dise...,...,NaN,0.592,0.960,0.740,0.000,0.000,0.009,0.122,4.25,-2.780